[build]
  command = "npm run build"
  publish = "dist/client/"

[functions]
  directory = "functions/"
  external_node_modules = ["@brillout/vite-plugin-import-build", "@brillout/import", "vite-plugin-ssr"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/generatePage"
  status = 200
  force = false
